/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import static Project.New_cust.ag;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author hp1
 */
public class Main_page extends javax.swing.JFrame {
    //Global connection classes.
      
    //static Map<String, List<List<String>>> map = new HashMap<>();
    static Map<String, List<String>> map = new HashMap<>();
     //static List< List<String>> ls1 = new ArrayList<>();
     static List<String> ls4 = new ArrayList<>();
    /**
     * Creates new form Main_page
     */
    public Main_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Complaint");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Officer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(44, 44, 44)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Select_type st = new Select_type();
st.setVisible(true);
    this.setVisible(false);
    //Use of a HashMap and two ArrayList so that we can search quickly. All the data is tranferred into
    //HashMap on entry.
    try {
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/comp","shibli","shibli");
            Statement stm = (Statement)con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from cmp;");
            int h =1;
            while(rs.next()==true){
            List<String> ls1 = new ArrayList<>();
            ls1.add(rs.getString("name"));
            ls1.add(rs.getString("age"));
            ls1.add(rs.getString("occup"));
            ls1.add(rs.getString("pnum"));
            ls1.add(rs.getString("categ"));
            ls1.add(rs.getString("detail"));
            ls1.add(rs.getString("id"));
            ls1.add(rs.getString("status"));
            ls1.add(rs.getString("credit"));
            ls1.add(rs.getString("FeePaid"));
            map.put(rs.getString("id"), ls1);
            //System.out.println(ls1);
            h++;
            }
            //System.out.println(map);
        } catch (SQLException ex) {
            Logger.getLogger(New_cust.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Officer_log ol = new Officer_log();
        ol.setVisible(true);
        this.setVisible(false);
        try {
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/comp","shibli","shibli");
            Statement stm = (Statement)con.createStatement();
            ResultSet rs = stm.executeQuery("Select * from cmp;");
            int kl=0;
            while(rs.next()==true){
            List<String> ls4 = new ArrayList<>();
            ls4.add(rs.getString("name"));
            ls4.add(rs.getString("age"));
            ls4.add(rs.getString("occup"));
            ls4.add(rs.getString("pnum"));
            ls4.add(rs.getString("categ"));
            ls4.add(rs.getString("detail"));
            ls4.add(rs.getString("id"));
            ls4.add(rs.getString("status"));
            ls4.add(rs.getString("credit"));
            ls4.add(rs.getString("FeePaid"));
            //map1.put(rs.getString("id"),ls1);
            map.put(rs.getString("id"), ls4);
            }
            //JOptionPane.showMessageDialog(null,"");
        } catch (SQLException ex) {
            Logger.getLogger(New_cust.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
